import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner/banner";
import Card from "../components/card/card";
import SectionCards from "../components/card/Section-Cards";
import Navbar from "../components/nav/navbar";
import styles from "../styles/Home.module.css";
import { getVideo } from "../lib/videos";

export async function getServerSideProps() {
  const disneyVideos = await getVideo("disney trailer");
  const productivityVideos = await getVideo("productivity");
  const travelVideos = await getVideo("travel");
  // const popularVideos = await getVideo("disney trailer");

  return { props: { disneyVideos, productivityVideos, travelVideos } };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="solomon@thedrycleanersson.com" />
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Travel" videos={travelVideos} size="small" />{" "}
        <SectionCards
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        />{" "}
        <SectionCards title="Popular" videos={disneyVideos} size="small" />
      </div>
    </div>
  );
}
